### PR TITLE
chore: supporting video thumbnails

### PR DESCRIPTION
**Pull request by ximxim**
## Deploy Notes

Notes regarding deployment of the contained body of work. These should note any
db migrations, nginx routes, infrastructure changes, and anything that must be done before deployment.

- [ ] Need to add environment variables
  - `ENV_VAR=`

### CODE REVIEW

**Comment by wilsoncusack** [comment]
@ximxim I think this broke this page--https://onchainsummer-xyz-git-azim-video-thumbnail-support-base-org.vercel.app/anotherblock?spoofDate=2023-08-17

let's check auto play

**Review by lauchness — APPROVED** [review]
Seems solid now

**Comment by cb-heimdall** [comment]
Review Error for lauchness @ 2023-08-16 13:32:57 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Comment by wilsoncusack** [comment]
zora declined

**Pull request closed without merging**
