### PR TITLE
fix: navigation menu overflow on desktop

### PR DESCRIPTION
**Pull request by rendinjast**
## Description

changed NavigationMenu.Root width to w-full

## Screenshots (if appropriate)
image

### CODE REVIEW

**Comment by nhodges** [comment]
@rendinjast Does this fix the body x blowout? If so, #201 can be closed in favor of this.

**Comment by rendinjast** [comment]
@nhodges yes also header alignment (see screenshot).

**Comment by wilsoncusack** [comment]
Thanks both! @lauchness can you review

**Review by lauchness — APPROVED** [review]
QA'ed and LGTM

**Comment by cb-heimdall** [comment]
Review Error for lauchness @ 2023-08-14 18:11:14 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Review by wilsoncusack — APPROVED** [review]

**Pull request merged**
